import os, sys, glob, tqdm
from PIL import Image
from colorthief import ColorThief

png_files = glob.glob("assets\\minecraft\\textures\\block\\*.png")

block_colors = {}
for p in tqdm.tqdm(png_files):
    color_thief = ColorThief(p)
    try:
        dominant_color = color_thief.get_color(quality=1)
    except Exception as e:
        print(f"Error: {e} on {p}")
        continue

    block = os.path.splitext(os.path.basename(p))[0].lower()
    # print(f"\"minecraft:{block}\": {dominant_color},")
    block_colors[f"{block}"] = dominant_color
    for subtype in ("stairs", "slab", "fence", "door", "trapdoor"):
        block_colors[f"{block}_{subtype}"] = dominant_color

with open("extracted_block_colors.py", "w") as f:
    f.write(f"# This file is generated by {os.path.basename(sys.argv[0])}\n")
    f.write("BLOCK_COLORS = {\n")
    for block, color in block_colors.items():
        f.write(f"    \"{block}\": {color},\n")
    f.write("}\n")